CREATE DATABASE IF NOT EXISTS greenvolts;
USE greenvolts;

CREATE TABLE IF NOT EXISTS Users (
    UserId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(120) NOT NULL,
    Email VARCHAR(180) NOT NULL UNIQUE,
    Password VARCHAR(200) NOT NULL,
    Role VARCHAR(50) NOT NULL DEFAULT 'Viewer',
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Services (
    ServiceId INT AUTO_INCREMENT PRIMARY KEY,
    ServiceName VARCHAR(180) NOT NULL,
    Slug VARCHAR(180) NOT NULL UNIQUE,
    Description TEXT NOT NULL,
    Image VARCHAR(300) DEFAULT '',
    Status VARCHAR(50) NOT NULL DEFAULT 'Published',
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ServiceDetails (
    DetailId INT AUTO_INCREMENT PRIMARY KEY,
    ServiceId INT NOT NULL,
    StudyName VARCHAR(180) NOT NULL,
    Description TEXT NOT NULL,
    CONSTRAINT FK_ServiceDetails_ServiceId FOREIGN KEY (ServiceId) REFERENCES Services(ServiceId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Projects (
    ProjectId INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(220) NOT NULL,
    Client VARCHAR(180) NOT NULL,
    Location VARCHAR(180) NOT NULL,
    Description TEXT NOT NULL,
    Image VARCHAR(300) DEFAULT '',
    Status VARCHAR(50) NOT NULL DEFAULT 'Completed'
);

CREATE TABLE IF NOT EXISTS Blogs (
    BlogId INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(220) NOT NULL,
    Slug VARCHAR(220) NOT NULL UNIQUE,
    Description TEXT NOT NULL,
    Image VARCHAR(300) DEFAULT '',
    Author VARCHAR(180) DEFAULT 'Greenvolts Team',
    PublishedDate DATETIME NULL,
    Category VARCHAR(80) DEFAULT 'General',
    Status VARCHAR(50) DEFAULT 'Draft'
);

CREATE TABLE IF NOT EXISTS Gallery (
    GalleryId INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(220) NOT NULL,
    Image VARCHAR(300) NOT NULL,
    Category VARCHAR(120) NOT NULL,
    MediaType VARCHAR(30) DEFAULT 'Image',
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Testimonials (
    TestimonialId INT AUTO_INCREMENT PRIMARY KEY,
    ClientName VARCHAR(180) NOT NULL,
    Company VARCHAR(180) NOT NULL,
    Review TEXT NOT NULL,
    Rating VARCHAR(20) NOT NULL,
    Photo VARCHAR(300) DEFAULT '',
    Status VARCHAR(50) DEFAULT 'Published'
);

CREATE TABLE IF NOT EXISTS FAQs (
    FAQId INT AUTO_INCREMENT PRIMARY KEY,
    Question VARCHAR(300) NOT NULL,
    Answer TEXT NOT NULL,
    Category VARCHAR(120) DEFAULT 'General',
    Status VARCHAR(50) DEFAULT 'Published'
);

CREATE TABLE IF NOT EXISTS Careers (
    CareerId INT AUTO_INCREMENT PRIMARY KEY,
    JobTitle VARCHAR(180) NOT NULL,
    Experience VARCHAR(180) NOT NULL,
    Location VARCHAR(180) NOT NULL,
    Description TEXT NOT NULL,
    Salary VARCHAR(100) DEFAULT '',
    Status VARCHAR(50) DEFAULT 'Open'
);

CREATE TABLE IF NOT EXISTS JobApplications (
    ApplicationId INT AUTO_INCREMENT PRIMARY KEY,
    CareerId INT NOT NULL,
    Name VARCHAR(180) NOT NULL,
    Email VARCHAR(180) NOT NULL,
    Phone VARCHAR(50) DEFAULT '',
    Resume VARCHAR(300) DEFAULT '',
    Status VARCHAR(50) DEFAULT 'New',
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_JobApplications_CareerId FOREIGN KEY (CareerId) REFERENCES Careers(CareerId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ContactEnquiries (
    EnquiryId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(180) NOT NULL,
    Company VARCHAR(180) DEFAULT '',
    Email VARCHAR(180) NOT NULL,
    Phone VARCHAR(50) DEFAULT '',
    RequiredService VARCHAR(180) DEFAULT '',
    Message TEXT NOT NULL,
    Status VARCHAR(50) DEFAULT 'Unread',
    CreatedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Settings (
    SettingId INT AUTO_INCREMENT PRIMARY KEY,
    CompanyName VARCHAR(180) NOT NULL,
    Logo VARCHAR(300) DEFAULT '',
    Address VARCHAR(500) DEFAULT '',
    Phone VARCHAR(50) DEFAULT '',
    Email VARCHAR(180) DEFAULT '',
    WorkingHours VARCHAR(120) DEFAULT '',
    Facebook VARCHAR(300) DEFAULT '',
    LinkedIn VARCHAR(300) DEFAULT '',
    Instagram VARCHAR(300) DEFAULT '',
    Twitter VARCHAR(300) DEFAULT '',
    GoogleMap VARCHAR(400) DEFAULT '',
    SeoTitle VARCHAR(220) DEFAULT '',
    SeoDescription VARCHAR(500) DEFAULT ''
);
